version: '3.3'
services:
  med-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: med-db
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: psql -U dbuser -d med-db -c "select 1"
      interval: 10s
      timeout: 5s
      retries: 5
  med-api:
    container_name: med-api
    build: .
    image: node:18
    depends_on:
      - med-db
    ports:
      - 3000:3000
    command: ["./med-api-startup.sh"]
    environment:
      NODE_ENV: development
      DB_HOST: med-db
      DB_PORT: 5432
      DB_USER: dbuser
      DB_PASSWORD: dbpassword
      DB_NAME: med-db
      JWT_SECRET: secret
      FCM_SERVICE_KEY: '{"type": "service_account", "project_id": "rn-notifications-a37b3", "private_key_id": "18565f33bcce831b9f522a62617bf0e908ac78e6", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCnxOjAl64A4rc0\nAIBX0FVzL4X7sXvcuT5H8JqFT/wxMDzUjjoyPR+ENbR8OkdJH5wSV0ug8/i5hCIe\nWtAD9bzhi5ry2Ij8gvFkyqZKUqckUBcxX7+P0kZHtMCJWGivuVQ3BhzQnz/Hj8Yr\nEQYq6CTODhnRO4/9ykcB/MiH5XjugybV8FUK6vv2bq6W/choIQZ12yzYTLTpWknw\nZh6SDcDlenvIMmHcUSQ24NPYN6pEl43qspwvW2ER+WjLfg7vPkesgkhBn15ZGT8U\nK+E/2qInv80GLqcyGF/1N2/O7AgAmwvbTS++qLfLp/ovDEwKiCUMW0XUIWvWTaDe\nCrmBridFAgMBAAECgf9dbBAwEn+ZxcI+3ZbTT4UpZk1SMEo6u5dksOwFiUvmGC9V\nu92P410bQiIGJ8MYn7plmKihFI/B2wtdovtPOTK79DpxAJUOsoadC5EcQ83ro5FG\ntGAURK4zeMkTskPusu+kJhiQTI9UAxEeBrIvpDIv4XFig6wAbk3/zVIWWrI1rF2C\nPT2TcMDn1SXwUOaEx19gfUTXfUY6PQpcfvbJUArvnRFyHuhsp3WvMO3ofv51KBiR\nnwFRLR8tkA6pyqOe3LN5aCuRI5ExYvGfCcID2V7njnz5ihdDfZYX11ZdHw9hqp5V\n6iwxZ7kQmWcJaDevbD+IY8nNXeq4IIZc+XMSJoECgYEA190St5y3DiSBCcDWxg2a\nfagHWUTRfLMA6GCWq+8+ujl5YA53vAIC0dCFXuyEkM9lHNSF79Jgw0AEAt2vEcVJ\nJN4wogoS2TKqRvRRTHZYBn8BfuASR/r7NSyCX5H82P5PyoLwzEFDyh/GiVsIjNlW\nxtaJDeW+oFFyChf889/f2+ECgYEAxvaVPGQAQczikrDN6E/tfSaq9bM99Ef8Hgpb\niK0WKr1h38JebWddGIa1vZJX46rM4h2qi40juuoR6GqWk6taHs9SfMLdsEB0taqP\nrKK1ZQfZ7wPw9J6f7kZxcnBjWTR381MDe3CVkNfMP8xgEqFgk8O9fTkhpz+9nqw3\nNklVV+UCgYEAkX0sH1rdugd6fSNe3k/O34A/q7gJZX2UUArBopJ2ebdBCi/WHX5R\nfi6HpanN03glEyBeQXxOwWpFCdV2KIkKunGS37PgbkmKoJYMsXdV7tLtJCFL0P3l\nEDq2iElx3KLTDo/gUhpu4S03d95GTgAyT4PLDfXZ3F3oecsfLxOl4qECgYBuPgj4\nukwuKXFNaGvfEhJ8KuXFWDi21wAKQSDwvT8wFVla217o7cH2qgWfcawDOQtnKprp\n0h1/Ht0nU4/1aJd5xNRmzq55T22bj1Mmi81Imq4VsrBbSl1BcITBrSZPMjRYfaHL\nTtmAtSG2I+8Dw6k4lteyv+o2uqm9dpztFnsURQKBgHSW2ZjqtOd+WS0nlGxmH/jB\nTgwnN4n53um+l+V0zxm04TdcU7Ysf35fnduwVnvFIu1MqjYJBaBP2SFWIC8PmL5+\nR6NLLDqs6vDn5YyGrL6LFoccti1c8mXNLRKZCcJvxnkksUH8AlaGtcGTAzMTglcg\nkuLo02XPrfsQjc+GbcY/\n-----END PRIVATE KEY-----\n",  "client_email": "firebase-adminsdk-ybfpa@rn-notifications-a37b3.iam.gserviceaccount.com",  "client_id": "114279259405619026806",  "auth_uri": "https://accounts.google.com/o/oauth2/auth",  "token_uri": "https://oauth2.googleapis.com/token",  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ybfpa%40rn-notifications-a37b3.iam.gserviceaccount.com",  "universe_domain": "googleapis.com"}'
    volumes:
      - './:/med-server'
    working_dir: /med-server
